### ISSUE TITLE
TypeError when pasting

### ISSUE THREAD

**Issue by wheelercj** [PythonistaGuild/mystbin.py#6]
### Summary

mystbin_client.create_paste raises TypeError

### Reproduction Steps

* Python version: 3.10.0
* mystbin.py version: 5.0.0, installed with `pip install mystbin.py`
* OS: Windows 10

### Minimal Reproducible Code

```python
mystbin_client = mystbin.Client(session=self.bot.session)
paste = await mystbin_client.create_paste(filename="12345.txt", content="sample text", syntax="txt")
```

### Expected Results

An exception would not be raised.

### Actual Results

```
Traceback (most recent call last):
  File "C:\Users\chris\Documents\programming\Parhelion\venv\lib\site-packages\discord\ext\commands\core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\chris\Documents\programming\Parhelion\cogs\other.py", line 129, in share
    paste = await mystbin_client.create_paste(
  File "C:\Users\chris\Documents\programming\Parhelion\venv\lib\site-packages\mystbin\client.py", line 77, in create_paste
    return Paste._from_data(data)
  File "C:\Users\chris\Documents\programming\Parhelion\venv\lib\site-packages\mystbin\paste.py", line 159, in _from_data
    files = [File._from_data(data) for data in payload["files"]]
TypeError: string indices must be integers
```

I printed the string and got this:

```py
payload = '{"id":"ClassicVcrDod","author_id":null,"created_at":"2022-08-29T05:50:31.375809+00:00","expires":null,"files":[{"filename":"20220829055032.txt","content":"test","loc":1,"charcount":4}],"notice":null}'
```

The string hadn't been converted to a dict like it should have been.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [ ] I have included debug logging (with my latest token remove), if applicable.

### Additional Context

Looks like this is what is happening:
1. HTTPClient.request [can return a str](https://github.com/PythonistaGuild/mystbin.py/blob/a3d3f1ed51ca28a36012ed7778c82ac003d33524/mystbin/http.py#L202)
2. . . . to HTTPClient._create_paste which then [returns a str](https://github.com/PythonistaGuild/mystbin.py/blob/a3d3f1ed51ca28a36012ed7778c82ac003d33524/mystbin/http.py#L261)
3. . . . to Client.create_paste which [gives the str](https://github.com/PythonistaGuild/mystbin.py/blob/a3d3f1ed51ca28a36012ed7778c82ac003d33524/mystbin/client.py#L77)
4. . . . to [Paste._from_data](https://github.com/PythonistaGuild/mystbin.py/blob/a3d3f1ed51ca28a36012ed7778c82ac003d33524/mystbin/paste.py#L158) which requires a PasteResponse (a TypedDict subclass), not a str

A simple workaround that I tested is to add this to the top of Paste._from_data:
```py
if isinstance(payload, str):
    payload: dict = json.loads(payload)
```

But I'm not sure if HTTPClient.request should never return a str instead.

Thanks for all of your work on this repo!

**Comment by AbstractUmbra** [comment]
Hey, thanks for letting me know.

I actually knew about this error already. Currently the `PUT /paste` request we send to mystbin's backend API does not return the `application/json` content type header, so when I parse the response it assume it is not JSON to avoid an error... thereby causing a fun new one.
I'm wondering if I should skip this and *assume* it's json for now, until we fix the backend.

**Comment by AbstractUmbra** [comment]
This will now be fixed when https://github.com/PythonistaGuild/MystBin/commit/efc936c28da89bc95070a7b70ae91978e0337e42 is made into a release and deployed.

**Comment by AbstractUmbra** [comment]
I got that commit and made it into a release, this should be resolved now. Feel free to re-open if not!

**Comment by wheelercj** [comment]
Awesome, it works! Thanks!
