### ISSUE TITLE
Unclosed client session

### ISSUE THREAD

**Issue by ytcalifax** [PythonistaGuild/mystbin.py#9]
### Summary

There seems to be an unclosed client session that is left, causing an error

### Reproduction Steps

Just use the library as normal - create a paste.

### Minimal Reproducible Code

```python
from mystbin import Client

url = await Client().create_paste(filename=''.join(random.choices(string.ascii_lowercase, k=5)), content="Text")
```

### Expected Results

No errors in console

### Actual Results

Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001D30CE5B790>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001D30CE6E380>, 276911.281)]']
connector: <aiohttp.connector.TCPConnector object at 0x000001D30CE5B760>

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [ ] I have included debug logging (with my latest token remove), if applicable.

**Comment by chillymosh** [comment]
The provided example would fail as you are not awaiting inside a coroutine.

For example the following is a working example
```
import aiohttp
import mystbin
import asyncio

async def paste():
    async with aiohttp.ClientSession() as session:
        mystbin_client = mystbin.Client(session=session)
        p = await mystbin_client.create_paste(filename="Hello.py", content="Hello there!")
        print(p)

asyncio.run(paste())
```

**Comment by ytcalifax** [comment]
I am using it inside one, I just did not provide it here; the fact is, even in a coroutine and when properly awaited it still gives me the errors shown (using Win 22H2;latest Python 3)

**Comment by chillymosh** [comment]
Providing a session via a context manager will perform cleanup of the client session.

**Comment by ytcalifax** [comment]
I see, I'll redact my code accordingly. Isn't it a good idea to have this mentioned in the README too?

**Comment by chillymosh** [comment]
To run it in the way you wish to, then you'd have to call .close() on the Client, similar to every other connection based lib.
The README assumes users have this understanding.
```
from mystbin import Client
import asyncio
import random
import string

async def paste():
    client =  Client()
    p = await client.create_paste(filename=''.join(random.choices(string.ascii_lowercase, k=5)), content="Text")
    await client.close()
    print(p)

asyncio.run(paste())
```

**Comment by ytcalifax** [comment]
I see. Thanks for the quick response.
